# Generated by Django 6.0.2 on 2026-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='Jo Bidon', max_length=50),
        ),
    ]
