# Generated by Django 6.0.2 on 2026-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
