# Generated by Django 6.0.2 on 2026-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='Unknown', max_length=40),
            preserve_default=False,
        ),
    ]
