# Generated by Django 6.0.2 on 2026-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text2',
            field=models.CharField(default='qwe', max_length=150),
        ),
    ]
