# Generated by Django 6.0.2 on 2026-03-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_comments_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text2',
        ),
    ]
