# Generated by Django 6.0.2 on 2026-03-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_comments_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='user',
        ),
    ]
